### ISSUE TITLE
Header gap

### ISSUE THREAD

**Issue by dlzi** [cdwharton/HeadShrinker#1]
Hi guys.

Nice script you have. I'm playing with it and so far all good. But I just noticed that once I resize the browser's window (Chrome) and resize it back, there is a gap created by the header. It stay like that around 10s.

![header](https://f.cloud.github.com/assets/1160818/1088245/87d8fefe-162e-11e3-9442-e357352ac2d5.jpg)

Is that normal?

**Comment by cdwharton** [comment]
Well firstly, "normal" users don't resize their browser, its only us developers that do that! Secondly, the gap will close up within about 10 seconds.

**Comment by dlzi** [comment]
Haha.. yeah.. it's the habit!

So, I think having a double menu for around 15-20s is 'normal' for us developer too, right? :-)

![screen shot 2013-09-05 at 7 55 46 pm](https://f.cloud.github.com/assets/1160818/1088402/1bd25daa-1632-11e3-8e58-f54fe15a6e23.png)

**Comment by cdwharton** [comment]
you're gonna have to send a link if you want help debugging something

**Comment by dlzi** [comment]
Fair enough. It's a test site.

http://begun.theux.co/

Another thing I noticed is that once you scroll down and return to the top, the whole header is unaligned. You need to refresh the page to get it right.

**Comment by dlzi** [comment]
Hey guys,

I see that the logo doesn't shrink. Is that because the img element is not a directly descent from header?

**Comment by cdwharton** [comment]
Hi Daniel, try version 1.0.2 It should have fixed the logo issue for you. The unaligned header, is this an issue as everything is shrinking down, if you want to keep nav on the right, can this be achieved with a float? I'm hoping its also fixed the double menu issue, we couldn't actually replicate that, using a copy of your code. Please let us know what browser that occurs in if its still happening.

**Comment by dlzi** [comment]
Hey Chris,

It did work and I didn't see the double menu anymore too. Well done!

Thanks!

**Comment by dlzi** [comment]
Hey Chris,

Sorry for reopen this issue, but I found something. As you can see on the pic there is a gap between the header and the content. Plus, the hamburger doesn't fit in the header.

![screen shot 2013-09-07 at 8 53 21 pm](https://f.cloud.github.com/assets/1160818/1101391/569604fc-17c5-11e3-97c9-a2d60a701982.png)

You can see it live here http://begun.theux.co/lorem-ipsum/

**Comment by cdwharton** [comment]
It looks ok, but it looks like you've changed something anyway?

**Comment by dlzi** [comment]
Hey Chris,

Yeah, I was to write to you now. I did some changes and I noticed that if I let the site description on, it appears duplicated. If you scroll the page down the second description disappears, but if you refresh the page, it will appear again. Can you see that?

http://begun.theux.co/

**Comment by cdwharton** [comment]
Hi Daniel, I think you're trying to do something a little bit different to what HeadShrinker can provide, you're using rem values and a fixed height on the header for a start, which is going to effect native padding/margin calculations. I've removed HeadShrinker from your link (via Inspect Element) and the header area layout is broken anyway. HeadShrinker is designed for more simple headers, with an image + navigation. If I were you, I'd get it all working without the plugin in place first, then once you're happy with your CSS etc. put HeadShrinker back on again and see what happens. Its very difficult trying to solve an issue with an incompletely coded website, there are too many other factors.

**Comment by dlzi** [comment]
Thanks Chris. I'll work on a better header. 

Cheers.

**Comment by cdwharton** [comment]
Cool, I'll close this down for now, please re-open when you're closer to the end result.
