### ISSUE TITLE
Navigation Menu not working in mobile at all?

### ISSUE THREAD

**Issue by nickngqs** [cdwharton/HeadShrinker#2]
Hi, I've tried your main site with my phone. Android Gingerbread's native browser. The mobile nav is clickable, but when I clicked on sub-header, the sublinks appears causing the menu becomes longer (which is normal) but once I started scrolling the menu, the menu disappears.

**Comment by cdwharton** [comment]
Hi Nick, any chance you can do a video so I can see, I've not got Gingerbread to hand yet.

**Comment by nickngqs** [comment]
Hi, you can check them here, I've upload them to my site -> http://ruby-lab.com/video.html

Take note, view the website in Safari because I only embedded an mp4 video format. So Firefox, etc might not be able to view them, since they require ogg, webm etc..

The bug is on / off. Sometimes it works, sometimes it don't. Most of the times, the menu disappears.

**Comment by cdwharton** [comment]
Hi Nick, I thought we'd responded to this? If this is still an issue, please reopen and set up a working video link.
